import AppBar from '@/components/layout/appBar/appBar';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Image from 'next/image';
import SessionProvider from '@/components/auth/sessionProvider';

import { APP_NAME } from '@/helpers/consstants';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/helpers/auth/authOptions';
import { redirect } from 'next/navigation';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<SessionProvider>
				<body className={inter.className}>
					<Image
						src='/bg03.jpg'
						height={3024}
						width={3024}
						alt='Bakground image'
						className='fixed inset-0 -z-10 w-screen h-screen object-cover'
					/>

					<AppBar />

					<div className='px-10 py-5'>
						<h1 className='text-3xl text-center mb-14 mt-10'>
							{APP_NAME}
						</h1>
						{children}
					</div>
				</body>
			</SessionProvider>
		</html>
	);
}
