import AppBar from '@/components/layout/appBar';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Image from 'next/image';
import SessionProvider from '@/components/auth/sessionProvider';
import { useEffect } from 'react';
import { useRouter } from 'next/navigation';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<SessionProvider>
				<body className={inter.className}>
					<Image
						src='/bg3.jpg'
						height={3024}
						width={3024}
						alt='Bakground image'
						className='fixed inset-0 -z-10 w-screen h-screen object-cover'
					/>
					<AppBar />
					<div className='px-10 py-5'>{children}</div>
				</body>
			</SessionProvider>
		</html>
	);
}
